version: "3"
services:
  app:
    image: node:19
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    env_file: .env
    ports:
      - "4000:4000" # Mapeo del puerto del contenedor (5000) al puerto del host (5000)
    command: npm run dev
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: dbpasteleria
      POSTGRES_USER: pasteleria
      POSTGRES_PASSWORD: pasteleria1.
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
